const data = {
  products: [
    {
      _id: "1",
      name: "Blue Slim-Fit Blazer",
      category: "SportCoats",
      image: "/images/p1.jpg",
      price: "120",
      brand: "Stevie Harven",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Solid Red Blaze",
      category: "SportCoats",
      image: "/images/p2.jpg",
      price: "100",
      brand: "Raulf Luren",
      rating: 4.1,
      numReviews: 7,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Blue Slim-Fit Suit",
      category: "Men's Suits",
      image: "/images/p3.jpg",
      price: "220",
      brand: "Stevie Harven",
      rating: 4.2,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Tan Long Coat",
      category: "SportCoats",
      image: "/images/p4.jpg",
      price: "400",
      brand: "Prince Albert",
      rating: 5,
      numReviews: 7,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Pink Blazer",
      category: "SportCoats",
      image: "/images/p5.jpg",
      price: "180",
      brand: "Shawn Juan",
      rating: 4.7,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Striped Polo Shirt",
      category: "Shirts",
      image: "/images/p6.jpg",
      price: "60",
      brand: "Raulf Luren",
      rating: 4,
      numReviews: 7,
      description: "high quality product",
    },
  ],
};

export default data;
